import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { TanstackQueryProvider } from '@/providers'
import { I18nProviderClient } from '@/locales/client'

interface RootLayoutProps {
    children: React.ReactNode
    params: { locale: string }
}

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children,
  params: { locale }
}: RootLayoutProps) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <TanstackQueryProvider>
          <I18nProviderClient locale={locale}>
            {children}
          </I18nProviderClient>
        </TanstackQueryProvider>
      </body>
    </html>
  )
}